package render

import (
	"fmt"
	"html"
	"strings"

	"bound/internal/model"
)

// MermaidHTML renders a standalone architecture review page. Mermaid itself
// is loaded from its browser distribution so the generated artifact stays
// small and can be opened directly in a browser.
func MermaidHTML(a *model.Architecture) string {
	type diagram struct {
		Title string
		Body  string
	}
	diagrams := []diagram{
		{Title: "Context relationships", Body: contextDiagram(a)},
		{Title: "Component view", Body: componentDiagram(a)},
		{Title: "Interaction view", Body: interactionDiagram(a)},
		{Title: "Contracts and modules", Body: contractDiagram(a)},
		{Title: "Source ownership", Body: sourceDiagram(a)},
	}

	var b strings.Builder
	b.WriteString(`<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Architecture: `)
	b.WriteString(html.EscapeString(a.Name))
	b.WriteString(`</title>
  <style>
    :root { color-scheme: dark; --bg: #0f172a; --panel: #111827; --line: #334155; --text: #e5e7eb; --muted: #94a3b8; --accent: #818cf8; }
    * { box-sizing: border-box; }
    body { margin: 0; background: var(--bg); color: var(--text); font: 15px/1.55 -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; }
    main { max-width: 1600px; margin: 0 auto; padding: 40px 28px 72px; }
    header { border-bottom: 1px solid var(--line); margin-bottom: 28px; padding-bottom: 24px; }
    h1 { margin: 0 0 8px; font-size: clamp(28px, 4vw, 46px); letter-spacing: -0.03em; }
    h2 { margin: 0; font-size: 20px; }
    p { color: var(--muted); margin: 8px 0 0; }
    code { color: #c4b5fd; }
    .grid { display: grid; gap: 24px; }
    .card { background: var(--panel); border: 1px solid var(--line); border-radius: 12px; overflow: hidden; }
    .card-header { align-items: center; display: flex; justify-content: space-between; gap: 16px; padding: 16px 18px; }
    .diagram { background: #0b1120; border-top: 1px solid var(--line); min-height: 240px; overflow: auto; padding: 24px; }
    .diagram svg { height: auto; max-width: none; min-width: 720px; }
    .controls { display: flex; gap: 6px; }
    button { background: #1e293b; border: 1px solid #475569; border-radius: 6px; color: var(--text); cursor: pointer; padding: 5px 10px; }
    button:hover { background: #334155; }
    .fullscreen { background: var(--bg); inset: 0; overflow: auto; padding: 24px; position: fixed; z-index: 10; }
    .fullscreen .diagram { min-height: calc(100vh - 110px); }
    .fullscreen .diagram svg { min-width: 100%; }
    .error { color: #fecaca; font-family: monospace; white-space: pre-wrap; }
    @media (max-width: 700px) { main { padding: 24px 14px 48px; } .card-header { align-items: flex-start; flex-direction: column; } }
  </style>
  <script type="module">
    import mermaid from "https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.esm.min.mjs";
    mermaid.initialize({ startOnLoad: false, theme: "dark", securityLevel: "strict" });
    const zoom = new WeakMap();
    const render = async () => {
      const nodes = [...document.querySelectorAll(".mermaid-source")];
      for (let index = 0; index < nodes.length; index += 1) {
        const source = nodes[index];
        const host = source.parentElement;
        try {
          const { svg } = await mermaid.render("bound-diagram-" + index, source.textContent);
          host.innerHTML = svg;
          zoom.set(host, 1);
        } catch (error) {
          host.innerHTML = "<div class=\"error\">" + String(error) + "</div>";
        }
      }
    };
    const scale = (host, factor) => {
      const next = Math.max(0.35, Math.min(2.5, (zoom.get(host) || 1) * factor));
      zoom.set(host, next);
      const svg = host.querySelector("svg");
      if (svg) svg.style.transform = "scale(" + next + ")";
      if (svg) svg.style.transformOrigin = "top left";
    };
    document.addEventListener("click", (event) => {
      const button = event.target.closest("button[data-action]");
      if (!button) return;
      const card = button.closest(".card");
      if (button.dataset.action === "in") scale(card.querySelector(".diagram"), 1.2);
      if (button.dataset.action === "out") scale(card.querySelector(".diagram"), 1 / 1.2);
      if (button.dataset.action === "reset") {
        const host = card.querySelector(".diagram");
        zoom.set(host, 1);
        const svg = host.querySelector("svg");
        if (svg) svg.style.transform = "scale(1)";
      }
      if (button.dataset.action === "fullscreen") card.classList.toggle("fullscreen");
    });
    render();
  </script>
</head>
<body>
  <main>
    <header>
      <h1>Architecture: `)
	b.WriteString(html.EscapeString(a.Name))
	b.WriteString(`</h1>
      <p>Implementation: <code>`)
	b.WriteString(html.EscapeString(a.Implementation.Language))
	b.WriteString(`</code> at <code>`)
	b.WriteString(html.EscapeString(a.Implementation.Locator))
	b.WriteString(`</code></p>
      <p>Generated by Bound. Diagrams are interactive: zoom, reset, and fullscreen controls are available on each view.</p>
    </header>
`)
	for _, item := range diagrams {
		fmt.Fprintf(&b, `    <section class="card">
      <div class="card-header"><h2>%s</h2><div class="controls"><button data-action="out" aria-label="Zoom out">−</button><button data-action="reset">Reset</button><button data-action="in" aria-label="Zoom in">+</button><button data-action="fullscreen">Fullscreen</button></div></div>
      <div class="diagram"><pre class="mermaid-source">%s</pre></div>
    </section>
`, html.EscapeString(item.Title), html.EscapeString(item.Body))
	}
	b.WriteString(`  </main>
</body>
</html>
`)
	return b.String()
}
